theme = "catppuccin_mocha"

[editor]
# idle-timeout = 0
end-of-line-diagnostics = "hint"
completion-timeout = 5
completion-trigger-len = 3
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
rainbow-brackets = true

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
center = ["spinner", "spacer", "diagnostics"]
left = ["mode", "spacer", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["version-control", "spacer", "selections", "register", "position", "file-encoding"]
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[keys.insert]
"C-backspace" = "delete_word_backward"
"C-h" = "move_char_left"
"C-l" = "move_char_right"
"C-j" = "move_visual_line_down"
"C-k" = "move_visual_line_up"
# disable movements
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
# Go to normal mode faster
A-l = "normal_mode"


[keys.normal]
"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"
"esc" = ["collapse_selection", "keep_primary_selection"]

"C-k" = "jump_view_up"
"C-j" = "jump_view_down"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"

# TODO: change this when helix implements line movements
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal.space]
"x" = ":buffer-close"
