[[language]]
name = "ziex"
language-id = "zx"
scope = "source.zx"
roots = ["build.zig", "zls.json", ".git"]
file-types = ["zx"]
grammar = "zx"
language-servers = ["zls-zx"]
formatter = { command = "zx", args = ["fmt", "--stdio"] }
auto-format = true

[language-server.zls-zx]
command = "zls-zx-proxy"
args = ["zls"]

[[grammar]]
name = "zx"
source = { git = "https://github.com/nurulhudaapon/ziex", rev = "main", subpath = "pkg/tree-sitter-zx" }

[[language]]
name = "zig"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "latex"
language-servers = [ { name = "texlab" } ]

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true
executable = "latexmk"
pdfDirectory = "build"
# args = [
#   "-X",
#   "compile",
#   "%f",
#   "--synctex",
#   "--keep-logs",
#   "--keep-intermediates",
#   "--outdir=build",
#   "-Zshell-escape",
# ]
args = [
  "-pdf",
  "-interaction=nonstopmode",
   "-synctex=1",
   "-outdir=build",
   "%f"
]

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

[[language]]
name = "typst"

auto-format = true
formatter.command = "typstyle"
language-servers = [ { name = "tinymist" } ]

[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
# outputPath = "$root/build/document.pdf"
exportPdf = "onType"
# exportPdf = "never"
# formatterMode = "typstyle"
# preview.background.enabled = true
# preview.background.args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"]


[language-server.typescript-language-server.config]
plugins = [{  name = "@vue/typescript-plugin", location = "/usr/lib/node_modules/@vue/language-server", languages = ["vue"] }]
tsserver = { path = "/usr/bin/typescript-language-server" }

[language-server.vuels]
command = "vue-language-server"
args = ["--stdio"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "superhtml"
scope = "source.superhtml"
roots = []
file-types = ["shtml"]
injection-regex = "shtml|superhtml"
grammar = "html"
auto-format = true
language-servers = ["superhtml"]

[[language]]
name = "vue"
auto-format = true
language-servers = ["typescript-language-server", "vuels"]
formatter = { command = 'prettier', args = ["--parser", "vue"] }

[[language]]
scope = "source.svx"
name = "svx"
injection-regex = "md|markdown"
file-types = ["svx"]
grammar = "markdown"
language-servers = [ "svelteserver"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "markdown"
language-servers = ["marksman", "markdown-oxide", "harper-ls"]

# Ziggy

[language-server.ziggy-lsp]
command = "ziggy"
args = ["lsp"]

[[language]]
name = "ziggy"
scope = "text.ziggy"
roots = []
injection-regex = "ziggy|zgy"
file-types = ["ziggy", "zgy"]
comment-token = "//"
auto-format = true
formatter = { command = "ziggy" , args = ["fmt", "--stdin"] }
language-servers = [ "ziggy-lsp" ]

[[grammar]]
name = "ziggy"
source = { git = "https://github.com/kristoff-it/ziggy", rev = "0e46579ed878bb28a78cf624c2e593eb39301648", subpath = "tree-sitter-ziggy" }

[[language]]
name = "ziggy_schema"
scope = "text.ziggy_schema"
roots = []
injection-regex = "ziggy-schema|zgy-schema"
file-types = ["ziggy-schema", "zgy-schema"]
comment-token = "///"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "ziggy" , args = ["fmt", "-", "--type", "schema"] }
auto-format = true
language-servers = [ "ziggy-schema-lsp" ]

[[grammar]]
name = "ziggy_schema"
source = { git = "https://github.com/kristoff-it/ziggy", rev = "0e46579ed878bb28a78cf624c2e593eb39301648", subpath = "tree-sitter-ziggy-schema" }

[language-server.ziggy-schema-lsp]
command = "ziggy"
args = ["lsp", "--schema"]

# Supermd

[[language]]
name = "supermd"
scope = "source.supermd"
roots = []
file-types = ["smd"]
injection-regex = "supermd|smd"

[[grammar]]
name = "supermd"
source = { git = "https://github.com/kristoff-it/supermd", rev = "main", subpath = "tree-sitter/supermd" }

[[language]]
name = "supermd_inline"
scope = "source.supermd.inline"
injection-regex = "supermd_inline"
file-types = []
grammar = "supermd_inline"

[[grammar]]
name = "supermd_inline"
source = { git = "https://github.com/kristoff-it/supermd", rev = "main", subpath = "tree-sitter/supermd-inline" }
