#!/usr/bin/env bash
#
#  ███████╗ ██████╗██████╗ ███████╗███████╗███╗   ██╗    ██╗      ██████╗  ██████╗██╗  ██╗
#  ██╔════╝██╔════╝██╔══██╗██╔════╝██╔════╝████╗  ██║    ██║     ██╔═══██╗██╔════╝██║ ██╔╝
#  ███████╗██║     ██████╔╝█████╗  █████╗  ██╔██╗ ██║    ██║     ██║   ██║██║     █████╔╝
#  ╚════██║██║     ██╔══██╗██╔══╝  ██╔══╝  ██║╚██╗██║    ██║     ██║   ██║██║     ██╔═██╗
#  ███████║╚██████╗██║  ██║███████╗███████╗██║ ╚████║    ███████╗╚██████╔╝╚██████╗██║  ██╗
#  ╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═══╝    ╚══════╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝
#	gh0stzk - https://github.com/gh0stzk/dotfiles
#	15.10.2024 14:26:09
#	Dependencies - i3lock-color
#

TEMP_IMAGE="/tmp/i3lock.jpg"

bg='#11111b'
clear='#11111b'
ring='#b4befe'
fg='#cdd6f4'
date='#cdd6f4'
wrong='#f38ba8'
verify='#a6e3a1'

default_lockscreen () {
    i3lock-color -n --force-clock --screen 1 --blur 5 -e --indicator \
        --radius=30 --ring-width=60 --inside-color=$bg \
        --ring-color=$ring --insidever-color=$verify --ringver-color=$verify \
		--insidewrong-color=$wrong --ringwrong-color=$wrong --line-uses-inside \
		--keyhl-color=$verify --separator-color=$verify --bshl-color=$verify \
		--time-str="%H:%M" --time-size=140 --date-str="%a, %d %b" \
		--date-size=45 --verif-text="Verifying Password..." --wrong-text="Wrong Password!" \
		--noinput-text="" --greeter-text="Type the password to Unlock" --ind-pos="300:610" \
		--time-font="JetBrainsMono NF:style=Bold" --date-font="JetBrainsMono NF" --verif-font="JetBrainsMono NF" \
		--greeter-font="JetBrainsMono NF" --wrong-font="JetBrainsMono NF" --verif-size=23 \
		--greeter-size=23 --wrong-size=23 --time-pos="300:390" \
		--date-pos="300:450" --greeter-pos="300:780" --wrong-pos="300:820" \
		--verif-pos="300:655" --date-color=$date --time-color=$date \
		--greeter-color=$fg --wrong-color=$wrong --verif-color=$verify \
		--verif-pos="300:820" --pointer=default --refresh-rate=0 \
		--pass-media-keys --pass-volume-keys

}

rice_lockscreen () {

    # Wallpapers dir
    image_dir="$HOME/.dotfiles/Wallpapers/catppuccin/"

    # Select random image
    lock_image=$(find "$image_dir" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | shuf -n 1)

    i3lock-color -n --force-clock -i $lock_image --screen 1 --scale -e --indicator \
        --radius=30 --ring-width=60 --inside-color=$bg \
        --ring-color=$ring --insidever-color=$verify --ringver-color=$verify \
		--insidewrong-color=$wrong --ringwrong-color=$wrong --line-uses-inside \
		--keyhl-color=$verify --separator-color=$verify --bshl-color=$verify \
		--time-str="%H:%M" --time-size=140 --date-str="%a, %d %b" \
		--date-size=45 --verif-text="Verifying Password..." --wrong-text="Wrong Password!" \
		--noinput-text="" --greeter-text="Type the password to Unlock" --ind-pos="300:610" \
		--time-font="JetBrainsMono NF:style=Bold" --date-font="JetBrainsMono NF" --verif-font="JetBrainsMono NF" \
		--greeter-font="JetBrainsMono NF" --wrong-font="JetBrainsMono NF" --verif-size=23 \
		--greeter-size=23 --wrong-size=23 --time-pos="300:390" \
		--date-pos="300:450" --greeter-pos="300:780" --wrong-pos="300:820" \
		--verif-pos="300:655" --date-color=$date --time-color=$date \
		--greeter-color=$fg --wrong-color=$wrong --verif-color=$verify \
		--verif-pos="300:820" --pointer=default --refresh-rate=0 \
		--pass-media-keys --pass-volume-keys

}

case $1 in
    -r|--rice)
        rice_lockscreen;;
    -h|--help)
		echo -e "ScreenLocker [options]
Note: If an option is not specified, the screen locks with a screenshot with a blur effect.

Options:
	[-r] [--rice]	Set the screen locker with a random wallpaper of the current theme.\n";;
    *)
        default_lockscreen;;
esac
