
format = """
$directory\
$all\
$fill\
$cmd_duration\
$jobs\
$time\
$line_break\
$username\
$character\
${custom.sudo}\
"""

# Inserts a blank line between shell prompt
add_newline = false
command_timeout = 250
palette = "catppuccin_mocha"

[directory]
truncation_length = 3

[fill]
symbol = " "

[cmd_duration]
min_time = 0
format = "[$duration]($style) "

[jobs]
symbol = "✿"
style = "bold red"

[time]
disabled = false

[line_break]
disabled = false

[username]
format = "[@$user]($style) "
style_user = "bold blue"
show_always = true

[character]
success_symbol = '[λ](bold green)'
error_symbol = "[✗](bold red)"

# Can I run root commands?
[custom.sudo]
description = "valid sudo timestamp marker"
command = "echo -n '#'"
format = "[$symbol$output]($style) "
style = "bold fg:bright-red"
when = "sudo -vn &>/dev/null"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
