# Inserts a blank line between shell prompts
add_newline = false

right_format = "$time"
command_timeout = 250

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[λ](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[✗](bold red)"

# Make prompt a single line instead of two lines
[line_break]
disabled = false


# Can run root commands?
[custom.sudo]
description = "valid sudo timestamp marker"
command = "echo -n '#'"
format = "[$symbol$output]($style) "
style = "bold fg:bright-red"
when = "sudo -vn &>/dev/null"


[time]
disabled = false
